added lora example
blues/note-tutorials pull request #23
Opened 2023-10-18 23:51 UTC by bsatrom

2023-10-19 01:09 UTC, zfields requested changes
You have insane tabs throughout.

Also, I would love to see you follow the pattern provided for all requests, but dealers choice.

2023-10-19 01:09 UTC, zfields commented on lora-tutorials/lora-notecard-application/lora-notecard-application.ino
> +  }
```suggestion
  if (J *req = notecard.newRequest("note.template")) {
    JAddStringToObject(req, "file", DATA_NOTEFILE);
    JAddNumberToObject(req, "port", DATA_PORT);
    if (J *body = JAddObjectToObject(req, "body")) {
      JAddNumberToObject(body, FIELD_TEMPERATURE, TFLOAT32);
      JAddNumberToObject(body, FIELD_VOLTAGE, TFLOAT32);
      JAddNumberToObject(body, "_time", TINT32);
      if (!notecard.sendRequest(req)) {
        debug.println("unable to set data template");
      }
    } else {
      JDelete(req);
    }
  }
```

2023-10-19 01:09 UTC, zfields commented on lora-tutorials/lora-notecard-application/lora-notecard-application.ino
> +#define	VAR_MINUTES	"minutes"
I would call this `TVAR_MINUTES`, so you know it was templated.

Also, I don't really see how it's different from `FIELD_xxxx`, which I would also replace with `TVAR_xxxx`. They are all variables from a template, regardless of whether it's qi, qo or env.

2023-10-19 15:52 UTC, bsatrom commented on lora-tutorials/lora-notecard-application/lora-notecard-application.ino
> +HardwareSerial debug(PIN_VCP_RX, PIN_VCP_TX);
yes

2023-10-20 21:30 UTC, zfields approved these changes

2023-10-20 21:30 UTC, zfields commented on lora-tutorials/lora-notecard-application/lora-notecard-application.ino
> +  rsp = notecard.requestAndResponse(notecard.newRequest("card.status"));
This is a dangerous habit.

How about using a new variable name, instead of reusing `rsp`?

2023-10-20 21:35 UTC, merged